docker:
  image: yegor256/rultor-image:1.3
assets:
  settings.xml: yegor256/home#assets/jpeek/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
install: |
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  pdd -f /dev/null
architect:
- paulodamaso
merge:
  script: |
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean --errors --settings ../settings.xml
deploy:
  script: |
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  sensitive:
    - settings.xml
  script: |-
    export GPG_TTY=$(tty)
    gpg --import /home/r/pubring.gpg
    gpg --allow-secret-key-import --no-tty --batch --import /home/r/secring.gpg
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pjpeek -Psonar -Pqulice -Psonatype --errors --settings ../settings.xml